import { TTextFont } from '@/utils/types/global'

export const initAllSupportedFonts = (): TTextFont[] => [
  {
    fontFamily: 'Be Vietnam Pro',
    loadFontURL: '/fonts/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf',
    fontStyle: 'normal',
    fontWeight: '400',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
  },
  {
    fontFamily: 'Poppins',
    loadFontURL: '/fonts/Poppins/FZ-Poppins-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Montserrat',
    loadFontURL: '/fonts/Montserrat/static/Montserrat-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Roboto',
    loadFontURL: '/fonts/Roboto/static/Roboto-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Playfair Display',
    loadFontURL: '/fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Cormorant Garamond',
    loadFontURL: '/fonts/Cormorant_Garamond/static/CormorantGaramond-Regular.ttf',
    fontStyle: 'normal',
    fontWeight: '400',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
  },
  {
    fontFamily: 'Space Mono',
    loadFontURL: '/fonts/Space_Mono/SpaceMono-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Lora',
    loadFontURL: '/fonts/Lora/static/Lora-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Dela Gothic One',
    loadFontURL: '/fonts/Dela_Gothic_One/DelaGothicOne-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Phudu',
    loadFontURL: '/fonts/Phudu/static/Phudu-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Honk',
    loadFontURL: '/fonts/Honk/Honk-Regular-VariableFont_MORF,SHLN.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Bungee Spice',
    loadFontURL: '/fonts/Bungee_Spice/BungeeSpice-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Jersey 25 Charted',
    loadFontURL: '/fonts/Jersey_25_Charted/Jersey25Charted-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Bungee Outline',
    loadFontURL: '/fonts/Bungee_Outline/BungeeOutline-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Dancing Script',
    loadFontURL: '/fonts/Dancing_Script/static/DancingScript-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'VT323',
    loadFontURL: '/fonts/VT323/VT323-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Amatic SC',
    loadFontURL: '/fonts/Amatic_SC/AmaticSC-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Patrick Hand',
    loadFontURL: '/fonts/Patrick_Hand/PatrickHand-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Alfa Slab One',
    loadFontURL: '/fonts/Alfa_Slab_One/AlfaSlabOne-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Saira Stencil One',
    loadFontURL: '/fonts/Saira_Stencil_One/SairaStencilOne-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Bitcount',
    loadFontURL: '/fonts/Bitcount/static/Bitcount-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Creepster',
    loadFontURL: '/fonts/Creepster/Creepster-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Nosifer',
    loadFontURL: '/fonts/Nosifer/Nosifer-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  {
    fontFamily: 'Emilys Candy',
    loadFontURL: '/fonts/Emilys_Candy/EmilysCandy-Regular.ttf',
    fontDisplay: 'swap',
    fontFormat: 'truetype',
    fontStyle: 'normal',
    fontWeight: '400',
  },
]
